version: '3.8'

# Define the services (containers) that will be run
services:
  # First service: Flask app
  flask_app:
    # Build the image from the Dockerfile in the parent directory
    build:
      context: ../
      dockerfile: ./Dockerfile
    # Set the name of the resulting image
    image: # to be added.
    # Mount local files/directories as volumes in the container
    volumes:
      - ./Scores.txt:/Scores.txt
    # Expose the container's port 5000 to host port 8777
    ports:
      - "5000:5000"
    # Set environment variables for the container
    environment:
      - FLASK_APP=MainScores.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    # Start the Flask app with "flask run" command
    command: [ "flask", "run",]
