version: '3.8'

services:
  # First service: Flask app
  wog:
    image: docker1906/wog-app:latest
    # Mount local files/directories as volumes in the container
    volumes:
      - ./scores.txt:/scores.txt
    ports:
      - "8777:8777"
